# Generated by Django 4.1 on 2022-12-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('linenos', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
            ],
        ),
    ]
