# Generated by Django 3.0.5 on 2022-12-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20221231_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
