# Generated by Django 4.1.2 on 2022-12-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup_master',
            new_name='signupuser',
        ),
    ]
