# Generated by Django 4.1.2 on 2022-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_signup_master_signupuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupuser',
            new_name='signup_master',
        ),
        migrations.AlterField(
            model_name='adduser',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
